import Head from 'next/head'
import { useEffect } from 'react'
import { Navbar } from '../../components/Navbar'
import { MENU_ITEMS } from '../../data/menu'
import { Footer } from '../../components/Footer'
import { NewAdForm } from '../../components/NewAdForm'
import { getUser } from "../../redux/features/userSlice";
import { useSelector } from "react-redux";
import { useRouter } from 'next/router'
import axios from 'axios';
import qs from 'qs'
import { HOST } from '../../data/config'

export default function ModifierAnnonce(props) {

  const user = useSelector(getUser);
  const router = useRouter();

  useEffect(() => {
    if (!user.user) {
      router.replace("/");
    }

    if (!props.result) {
      router.replace("/");
    }
  }, [props])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {user.user && props.result ? (
        <>
          <Navbar menu={MENU_ITEMS} active={"nav-ajouter-une-annonce"}></Navbar>

          {
            user.user.uid === props.result.postedBy && (
              <main>
                <NewAdForm data={props.result} background={"/images/annonce_bg.jpg"} title={"Ajouter une annonce"}></NewAdForm>
              </main>
            )
          }

          <Footer menu={MENU_ITEMS}></Footer>
        </>
      ) : ""}
    </>
  )
}

export async function getServerSideProps(ctx) {
  const res = await axios.request({
    method: "GET",
    url: `${HOST}/api/offers`,
    params: {
      getBy: "id",
      value: ctx.query.id
    },
    paramsSerializer: params => { return qs.stringify(params) }
  }).then((response) => { return response.data }).catch((error) => { console.log(error); return null; })

  return {
    props: {
      result: res ? res : null
    },
  };
};
