import Head from 'next/head'
import { useEffect } from 'react'
import { Navbar } from '../../../components/Navbar'
import { MENU_ITEMS } from '../../../data/menu'
import { Footer } from '../../../components/Footer'
import { Announce } from '../../../components/Announce'
import { getUser } from "../../../redux/features/userSlice";
import { useSelector } from "react-redux";
import { useRouter } from 'next/router'
import axios from 'axios';
import qs from 'qs'
import { HOST } from '../../../data/config'

export default function ModifierAnnonce(props) {

    const user = useSelector(getUser);
    const router = useRouter();

    useEffect(() => {

    }, [props])


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar menu={MENU_ITEMS} active={"nav-acheter"} forceWhite={true}></Navbar>

            <main>
                <Announce data={props.result}></Announce>
            </main>

            <Footer menu={MENU_ITEMS}></Footer>
        </>
    )
}

export async function getServerSideProps(ctx) {
    const res = await axios.request({
        method: "GET",
        url: `${HOST}/api/offers`,
        params: {
            getBy: "id",
            value: ctx.query.id
        },
        paramsSerializer: params => { return qs.stringify(params) }
    }).then((response) => { return response.data }).catch((error) => { console.log(error); return null; })
    console.log(res);
    return {
        props: {
            result: res ? res : null
        },
    };
};
