import Head from 'next/head'
import { Navbar } from '../components/Navbar'
import { Hero } from '../components/Hero'
import { MENU_ITEMS } from '../data/menu'
import { About } from '../components/About'
import { Services } from '../components/Services'
import { FeaturedProperties } from '../components/FeaturedProperties'
import { HOST } from '../data/config'
import { SERVICES_ITEMS } from '../data/services'
import axios from 'axios';
import { Testimony } from '../components/Testimony'
import { TESTIMONY_ITEMS } from '../data/testimonies'
import { Footer } from '../components/Footer'

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar menu={MENU_ITEMS} active={0}></Navbar>

      <main>
        {/* <Hero bg={"/images/hero.jpg"}></Hero>
        <About></About>
        <Services></Services> */}
        <Hero></Hero>
        <FeaturedProperties title={"Dernières annonces (Ventes)"} data={props.result}></FeaturedProperties>
        <Services services={SERVICES_ITEMS}></Services>
        <Testimony testimonies={TESTIMONY_ITEMS}></Testimony>
      </main>

      <Footer menu={MENU_ITEMS}></Footer>
    </>
  )
}

export async function getServerSideProps(ctx) {
  const res = await axios.request({
      method: "GET",
      url: `${HOST}/api/offers`,
      data: {
          getBy: "offerType",
          value: "buy",
          limit: 4
      }
  })

  return {
      props: {
          result: res.data ? res.data : []
      },
  };
};
