import Head from 'next/head'
import { useEffect } from 'react'
import { Navbar } from '../components/Navbar'
import { MENU_ITEMS } from '../data/menu'
import { Footer } from '../components/Footer'
import { getUser } from "../redux/features/userSlice";
import { useSelector } from "react-redux";
import { useRouter } from 'next/router'
import { Hero } from '../components/Hero'

export default function MonCompte(props) {

  const user = useSelector(getUser);
  const router = useRouter();

  useEffect(() => {
    if(!user.user){
      router.replace("/");
    }
    console.log(user.user);
  }, [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user.user && (
        <>
          <Navbar menu={MENU_ITEMS} active={"nav-ajouter-une-annonce"}></Navbar>

          <main>
              <Hero height={{mobile: "300px", desktop: "500px"}} background={"/images/account_bg.jpg"} title={`Bonjour ${user.user.displayName}`}></Hero>
          </main>

          <Footer menu={MENU_ITEMS}></Footer>
        </>
      )}
    </>
  )
}