import React from 'react'
import Head from 'next/head'
import { Navbar } from '../components/Navbar';
import { OffersList } from '../components/OffersList'
import { MENU_ITEMS } from '../data/menu';
import axios from 'axios';

export default function Search(props) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar menu={MENU_ITEMS} active={0}></Navbar>

            <main>
                <OffersList offers={props.result}></OffersList>
            </main>
        </>
    )
}

export async function getServerSideProps(ctx) {
    const { offerType, propertyType, location, maxBudget, minSurface } = ctx.query;

    const res = await axios.request({
        method: "GET",
        url: "http://localhost:3000/api/offers",
        data: {
            offerType: offerType,
            filters: [
                {
                    filterBy: "city",
                    value: location
                },
                {
                    filterBy: "propertyType",
                    value: propertyType
                }
            ]
        }
    })

    return {
        props: {
            result: res.data
        },
    };
};